### ISSUE TITLE
能否加个参数，可以指定是否渲染

### ISSUE THREAD

**Issue by netsafer** [zhegexiaohuozi/SeimiAgent#1]
能否加个参数，可以指定是否渲染。
如果不渲染，就是普通的http请求，不走webkit

**Comment by zhegexiaohuozi** [comment]
未来一段时间内seimiAgent开发核心应该还是基于WebKit的相关特性。普通请求代理后续再考虑吧，不过，欢迎pull request哦！

**Comment by netsafer** [comment]
那有点小遗憾哦，毕竟如果不想渲染的情况也蛮多，不能浪费资源

**Comment by zhegexiaohuozi** [comment]
不渲染的情况完全可以不需要经过seimiAgent呀，直接请求即可啊。
这里可以参考seimiCrawler 的实现。

另外，直连代理意义不是很大，直连这种场景在任何语言下都有非常成熟的方案，都能做的很好，也没必要到seimiagent 这里绕一圈的
