### ISSUE TITLE
centos can't run

### ISSUE THREAD

**Issue by oahzuw** [zhegexiaohuozi/SeimiAgent#2]
#  ./seimiagent -p 9527
./seimiagent: error while loading shared libraries: libwebp.so.5: cannot open shared object file: No such file or directory

downlaod this: http://www.linuxfromscratch.org/blfs/view/svn/general/libwebp.html   make && make install 
and can't run  error again.

# lsb_release -a
LSB Version:    :core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 5.8 (Final)
Release:        5.8
Codename:       Final

**Comment by zhegexiaohuozi** [comment]
Yeah,the default binary package need centos6+ and centos5 will be supproted in future.

**Comment by oahzuw** [comment]
We know, thanks for reply
