### ISSUE TITLE
seimicrawler采集出错无法回调handleErrorRequest函数

### ISSUE THREAD

**Issue by calonmo** [zhegexiaohuozi/SeimiAgent#23]
seimicrawler配合SeimiAgent使用，当SeimiAgent停止时，采集出错次数达到设置的阈值时，程序无法回调handleErrorRequest函数

**Comment by zhegexiaohuozi** [comment]
Fixed in https://github.com/zhegexiaohuozi/SeimiCrawler/releases/tag/v1.3.3
