### ISSUE TITLE
SeimiAgent has crashed

### ISSUE THREAD

**Issue by xmvper** [zhegexiaohuozi/SeimiAgent#3]
this is the all error information:

    HttpConnection::writeResponse called while state is not 'SendingHeaders', not proceeding with sending headers.
    HttpConnection::writeResponse called while state is not 'SendingHeaders', not proceeding with sending headers.
    HttpConnection::writeResponse called while state is not 'SendingHeaders', not proceeding with sending headers.

 detail
    
    base environment ：aliyun 1core 1G mem ，centos7
    runtime environment ：docker version 1.9.1
    start command : nohup ./seimiagent -p 12345 &
    when I request about 50times , it has been crashed

**Comment by xmvper** [comment]
this is url that I used : http://next.36kr.com/posts?start_on=2016-03-23

**Comment by zhegexiaohuozi** [comment]
try this  version http://seimidl.wanghaomiao.cn/seimiagent_linux_v1.1_x86_64.tar.gz

**Comment by xmvper** [comment]
thanks for reply,but unfortunately,it still have the same problom,attached file is detail information

**Comment by zhegexiaohuozi** [comment]
Maybe you need complie on docker by yourself,and I will  to fit docker as soon as possible.Thank you for report.
