### ISSUE TITLE
delay延迟设置无效，导致SeimiAgent奔溃

### ISSUE THREAD

**Issue by YdjJervis** [zhegexiaohuozi/SeimiAgent#4]
[seimi] TargetUrl[http://www.tianyancha.com/search/深圳市城市建设开发(集团)公司?type=company] process:100%
[Seimi] All load finished.
[seimi] TargetUrl[http://www.tianyancha.com/search/深圳市城市建设开发(集团)公司?type=company] STATS [10 requests total] [30.00% from cache] [0.00% pipelined] [0.00% SSL/TLS] [30.00% Zerocopy]
[seimi] TargetUrl[http://www.tianyancha.com/search/深圳市万科房地产有限公司?type=company] STATS [10 requests total] [10.00% from cache] [0.00% pipelined] [0.00% SSL/TLS] [40.00% Zerocopy]
[Seimi] Document render out over.
127.0.0.1 - - [05/07/2016 10:07:48] "POST /doload HTTP/1.1" 200 88849 5.815
HttpConnection::writeResponse called while state is not 'SendingHeaders', not proceeding with sending headers.
HttpConnection::writeResponse called while state is not 'SendingHeaders', not proceeding with sending headers.
HttpConnection::writeResponse called while state is not 'SendingHeaders', not proceeding with sending headers.
SeimiAgent has crashed.
You can go to https://github.com/zhegexiaohuozi/SeimiAgent/issues and report a bug.
段错误 (核心已转储)

现象：我在start(Request req)里面循环push的很多个请求，设置了SeimiAgent渲染时间1秒，Crawler类的delay位20秒，请求队列位默认的，运行的时候第一个请求是有延迟20秒，后面的没有延迟，SeimiAgent控制台直接打印了一堆所有链接的同时请求，然后就奔溃了。
问题：如何让每个请求完成后到下个请求都有延迟呢？SeimiAgent访问太快，目标网站就会要求输入验证码，谢谢！！！

**Comment by zhegexiaohuozi** [comment]
SeimiAgent运行环境呢，操作系统及版本，内存，是否为容器

**Comment by YdjJervis** [comment]
问题已经解决了，但是现在碰到另一个问题，某个网完全已经拒绝我的SeimiAgent访问了，现在正在想办法伪装成其它浏览器，请问有好的方法吗？希望SeimiAgent能提供这样的接口

**Comment by zhegexiaohuozi** [comment]
目前可以考虑设置并不断切换代理，下一版增加支持自定义UA
