### ISSUE TITLE
SeimiAgent无法build

### ISSUE THREAD

**Issue by YdjJervis** [zhegexiaohuozi/SeimiAgent#5]
环境：Ubuntu
准备：下载好指定的qtbase和qtwebkit到seimiagent的src/qt目录
操作：运行build.py脚本
结果：说缺少QtCore目录下的.h文件
尝试1：找到对应.h添加到inlude/QtCore目录，继续报写一个.h找不到。失败
尝试2：下载Qt安装，把QtCore目录拷贝到seimiagent里qtbase/include目录。失败，源代码报错了
期望结果：能说明运行需要哪些环境，以及那个环境需要怎么配置，对于Java开发者，希望能直接按流程跑通过后微微改下c代码就行了，但是跑不通就没办法愉快的玩耍了。希望能得到大神您的帮助，谢谢。

**Comment by zhegexiaohuozi** [comment]
自行编译是需要有写基础的。对于正常使用者推荐直接使用官网编译好的二进制文件。官网的版本在你的环境下运行有什么问题么？

**Comment by YdjJervis** [comment]
您好！请问自行编译需要怎样QT环境呢？我现在就安装了一个Qt Creater，打开也提示找不到Q开头的相关文件:
#include <QSettings>
#include <QNetworkCookie>
#include <QNetworkCookieJar>
#include <QVariantList>
#include <QVariantMap>
#include <QStandardPaths>)。

#include <QtNetwork/QNetworkAccessManager>
等等很多。
请问大概什么时候能够出一个可以设置QtWebkit的UA的接口呢？

**Comment by zhegexiaohuozi** [comment]
UA已在下一版开发计划之中
