### ISSUE TITLE
Agent报大量QFont::setPixelSize: Pixel size <= 0 (-1)

### ISSUE THREAD

**Issue by xiaoyao2102** [zhegexiaohuozi/SeimiAgent#8]
向Agent发送请求，网址为http://live.500.com/2h1.php
Agent的控制台报大量
QFont::setPixelSize: Pixel size <= 0 (-1)
一般情况是访问超时同时Agent会退出，偶尔可以解析成功

**Comment by zhegexiaohuozi** [comment]
操作系统，运行版本

**Comment by xiaoyao2102** [comment]
系统CentOS7，Agent版本1.2

**Comment by zhegexiaohuozi** [comment]
Fix in v1.2.1
